Enable recording with four channels with Behringer UMC404HD sound card
nordic-dev-net/hydrophonitor pull request #30
Opened 2023-09-14 11:23 UTC by satukoskinen

- Add udev rule to enable capture on 4 channels and set volume to max
- Move audio-recorder.nix to modules/audio-recorder/
- Update flake inputs

2023-09-14 16:12 UTC, juliuskoskela requested changes

2023-09-14 16:12 UTC, juliuskoskela commented on flake.nix
> +          ./modules/audio-recorder/audio-recorder.nix
Let's use the default.nix idiom here.

2023-09-14 16:12 UTC, juliuskoskela commented on modules/audio-recorder/audio-recorder.nix
I think it would be good if we could separate the Behringer spesific configurations into an option on the audio-recorder module or find out some other way to make them optional,

2023-09-14 16:12 UTC, juliuskoskela commented on modules/audio-recorder/umc404hd-autocapture.sh
here we should also separate the device specific configurations from the generic config.

2023-09-14 16:12 UTC, juliuskoskela commented on targets/raspberry-pi-4/default.nix
Should be `recording-batch-size` or something similar. Default should be much bigger, maybe 10 mins?

2023-10-12 14:24 UTC, satukoskinen commented on flake.nix
> +          ./modules/audio-recorder/audio-recorder.nix
Renamed

2023-10-12 14:25 UTC, satukoskinen commented on modules/audio-recorder/audio-recorder.nix
The udev rule is defined so that it is only applied when the specific sound card is attached (based on idVendor & idProduct), so I don't see any harm in including the rule by default. It could be split to a separate file, though.

2023-10-14 10:09 UTC, juliuskoskela approved these changes

2023-10-14 10:09 UTC, merged