Add service for exporting journalctl logs & fix startLimitInterval in service configs
nordic-dev-net/hydrophonitor pull request #36
Opened 2023-12-11 16:31 UTC by satukoskinen

This PR adds a logging service that exports journalctl logs to a file in `/output/logs` every five minutes. Upon first export, the log file name is defined as an environment variable and exported with `systemctl set-environment`, so that subsequent exports can overwrite the existing log file.

The service also contains another oneshot service to export logs to another file upon system shutdown. This is achieved by giving the export service a `Before = ["audio-recorder.service"];` unitConfig. Systemd applies the start order in reverse on shutting down, hence this ensures that this service starts before `audio-recorder.service` and exits only after `audio-recorder.service` has stopped. On exit, the command defined in `ExecStop` is executed.

What I could not get working with the shutdown log export was to include a timestamp in the file where logs are written. When I tried it with this ExecStop:
```
ExecStop = ''${pkgs.bash}/bin/bash -c "FILE=$(${pkgs.coreutils}/bin/date +"%Y_%m_%d-%H_%M_%S")_journalctl_on_shutdown.txt; echo \"Exporting logs at shutdown to $FILE\" && journalctl --boot 0 > ${config.services.journalctl-log-export.output-folder}/$FILE"'';
```

This is what showed up on journalctl:
```
Jan 15 18:09:28 nixos bash[1876]: Exporting logs at shutdown to /nix/store/2hvfch152hp91kf4rm8giiflg0ndqll9-unit-journalctl-log-export-on-shutdown.service_874c6b8984b84df7b3d6b2bead37ac03_/run/credentials/journalctl-log-export-on-shutdown.service-nixos__/var/lib_journalctl_on_shutdown.txt
Jan 15 18:09:28 nixos bash[1880]: /nix/store/xv90a9497jmi4v1hx1y007al4vrk555c-bash-5.2-p15/bin/bash: line 1: /output/logs//nix/store/2hvfch152hp91kf4rm8giiflg0ndqll9-unit-journalctl-log-export-on-shutdown.service_874c6b8984b84df7b3d6b2bead37ac03_/run/credentials/journalctl-log-export-on-shutdown.service-nixos__/var/lib_journalctl_on_shutdown.txt: No such file or directory
```

Hence, log file on shutdown is named simply journalctrl_on_shutdown.txt. This should not be an issue as the next upcoming change will place all output files to deployment-specific directories. 

In addition, this PR contains two fixes for service configs:
- fix for audio-recorder unitConfig `After` configuration. For some reason, `sound.target` does not appear to work as a target for the service so that it would only be started after `sound.target` is reached. However, `multi-user.target` does work.
- restoring `startLimitIntervalSec = 0;` in all services (with hydrophonitor-gps and depth-recorder versions updated in flake.lock

2023-12-11 16:39 UTC, juliuskoskela commented
I got something like this to work:

https://github.com/juliuskoskela/ghaf/blob/bpmp-virt/modules/hardware/nvidia-jetson-orin/virtualization/host/uarta-host/default.nix

```
wantedBy = ["bindSerial3100000.service"];
 
 ...
 
 wantedBy = ["multi-user.target"];
 after = ["enableVfioPlatform.service"];
```

2024-01-15 19:59 UTC, satukoskinen commented
Got shutdown log exporting to work, but one issue about file naming remains. I updated PR description accordingly.

2024-01-17 07:50 UTC, juliuskoskela commented
> Got shutdown log exporting to work, but one issue about file naming remains. I updated PR description accordingly.

Change scope of the PR and move file name fixing to a new issue. Then we merge.

2024-01-17 08:52 UTC, juliuskoskela requested changes
Let's add one more thing to this PR and all future PR's, i.e. documentation.

So as a part of this PR create the following:

- Folder `docs`
- Inside docs `docs/logging.md
- In `logging.md` describe our logging system, how it's set up, where the logs go and how the user is meant to retrieve and examine the logs.

2024-01-17 16:34 UTC, satukoskinen commented
Documentation for logging added.

2024-01-18 10:43 UTC, juliuskoskela approved these changes

2024-01-18 10:44 UTC, merged